-- Deploy ludotheque:version_1 to pg

BEGIN;

ALTER SCHEMA "public" OWNER TO "ludotheque";
CREATE TABLE "genre" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ
);
CREATE TABLE "platform" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ
);
CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pseudo" TEXT NOT NULL UNIQUE,
  "is_admin" BOOLEAN DEFAULT false,
  "password" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ
);
CREATE TABLE "game" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "released_on" TIMESTAMPTZ NOT NULL,
  "background_image" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ
);
CREATE TABLE "game_has_platform" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "game_id" INTEGER NOT NULL REFERENCES "game"("id") ON DELETE CASCADE,
  "platform_id" INTEGER NOT NULL REFERENCES "platform"("id") ON DELETE CASCADE,
  PRIMARY KEY ("game_id","platform_id"),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ
);
CREATE TABLE "game_has_genre" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "game_id" INTEGER NOT NULL REFERENCES "game"("id") ON DELETE CASCADE,
  "genre_id" INTEGER NOT NULL REFERENCES "genre"("id") ON DELETE CASCADE,
  PRIMARY KEY ("game_id","genre_id"),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ
);
CREATE TABLE "user_has_game" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "game_id" INTEGER NOT NULL REFERENCES "game"("id") ON DELETE CASCADE,
  PRIMARY KEY ("game_id","user_id"),
  "is_finished" BOOLEAN NOT NULL DEFAULT 'false',
  "is_prioritized" BOOLEAN NOT NULL DEFAULT 'false',
  "score" INTEGER,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ
);

ALTER TABLE "game" OWNER to "ludotheque";
ALTER TABLE "platform" OWNER to "ludotheque";
ALTER TABLE "genre" OWNER to "ludotheque";
ALTER TABLE "user" OWNER to "ludotheque";
ALTER TABLE "game_has_platform" OWNER to "ludotheque";
ALTER TABLE "game_has_genre" OWNER to "ludotheque";
ALTER TABLE "user_has_game" OWNER to "ludotheque";

CREATE VIEW all_games_with_infos AS
  SELECT game.id, game.name,
    array_agg(DISTINCT platform.id) AS platform_id, array_agg(DISTINCT platform.name) AS platform_name,
    game.released_on,
    array_agg(DISTINCT genre.id) AS genre_id, array_agg(DISTINCT genre.name) AS genre_name,
    game.background_image
  FROM game
    JOIN game_has_platform ON game_has_platform.game_id = game.id
    JOIN platform ON platform.id = game_has_platform.platform_id
    JOIN game_has_genre ON game_has_genre.game_id = game.id
    JOIN genre ON genre.id = game_has_genre.genre_id
  GROUP BY game.id, game.name, game.released_on, game.background_image;

ALTER VIEW public.all_games_with_infos OWNER TO ludotheque;

COMMIT;
