@protocol=http://
@host=localhost
@port=:3000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Create a new user in db
POST {{baseUrl}}/users/register
content-type: application/json

{
  "pseudo": "Tetu",
  "password": "test"
}

### Log in admin user
POST {{baseUrl}}/users/login
content-type: application/json

{
  "pseudo": "Tutu",
  "password": "test"
}

### Log out user
GET {{baseUrl}}/users/logout

### Get users list
GET {{baseUrl}}/users/

### Delete a user by pseudo
DELETE {{baseUrl}}/users/Test12