@protocol=http://
@host=localhost
@port=:3000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Get all movies from db
GET {{baseUrl}}/movies/toto

### Get movie infos with movieId
GET {{baseUrl}}/movies/2

### Get all movies for last season
GET {{baseUrl}}/movies/lastseason

### Get all movies by seasonId
GET {{baseUrl}}/movies/season/2

### Add new movie
POST {{baseUrl}}/movies/newmovie
content-type: application/json

{
  "french_title": "Le gentil test",
  "original_title": "The Red test",
  "poster_url": "https://image.tmdb.org/t/p/original/eByAzqYc1ncYkaoxsYupkvMOL8H.jpg",
  "directors": ["Emeric Pressburger","Michael Powell"],
  "release_date": "1948-09-06",
  "runtime": 133,
  "casting": ["Moira Shearer","Adolf Wohlbrück","Marius Goring","Léonide Massine","Robert Helpmann"],
  "presentation": "Je propose de regarder les chaussons rouges. Film de Powell et Pressburger (D''ailleurs vous pouvez vous jeter sur leurs autres films, Narcisse Noir, Le voyeur, ... Y''a rien à jeter). Pourquoi ? Parce qu''il est superbe. Que la scène du ballet, je ne m''en suis jamais vraiment remis. Voilà... J''espère que ça vous plaira autant qu''à moi !",
  "publishing_date": "2020-03-20",
  "user_id": 19,
  "season_id": 3,
  "movie_genres": ["test","test1"],
  "movie_languages": ["Pусский","English","Roumain"],
  "movie_countries": ["Dans une foret"]
}

### Update a new movie
PUT {{baseUrl}}/movies/modify/In the Mood for Love
content-type: application/json

{
  "runtime": 102,
  "presentation": "Le meilleur film de tous les temps, tout simplement. Tout est dit."
}

### Update a new movie
PUT {{baseUrl}}/movies/publishing/112
content-type: application/json

{
  "isPublished": true
}