@protocol=http://
@host=localhost
@port=:3000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Get all movies from db
GET {{baseUrl}}/movies

### Get movie infos with movieId
GET {{baseUrl}}/movies/2