@protocol=http://
@host=localhost
@port=:3000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}


### Get all comments with movieId
GET {{baseUrl}}/reviews/3

### Get all reviews fron user from on movie with userId and movieId
GET {{baseUrl}}/reviews/2/3

### Create a comment for movie with user id and movie id
POST {{baseUrl}}/reviews/2/10
content-type: application/json

{
  "comment": "bla bla bla double test"
}

### Update a comment for movie with user id and movie id
PUT {{baseUrl}}/reviews/2/10
content-type: application/json

{
  "comment": "frey"
}

### Delete a comment for movie with user id and movie id
DELETE {{baseUrl}}/reviews/2/2