@protocol=http://
@host=localhost
@port=:3000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Create a new user in db
POST {{baseUrl}}/users/register
content-type: application/json

{
  "pseudo": "colo",
  "mail": "new@test.fr",
  "password": "apero"
}

### Log user
POST {{baseUrl}}/users/login
content-type: application/json

{
  "pseudo": "colo",
  "mail": "new@test.fr",
  "password": "tata"
}

### Get all users from db
GET {{baseUrl}}/users

### Get user with userId
GET {{baseUrl}}/users/1