@protocol=http://
@host=localhost
@port=:3000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Create a new user in db
POST {{baseUrl}}/users/register
content-type: application/json

{ "pseudo": "Test", "mail": "Test@test.fr", "password": "Test" }

### Log user
POST {{baseUrl}}/users/login
content-type: application/json

{
  "pseudo": "Test2",
  "password": "Test"
}
### Log admin
POST {{baseUrl}}/users/login
content-type: application/json

{
  "pseudo": "Yves Signal",
  "password": "K_foDAInGDeXiN~bt/Bx"
}

### Refresh tokens
POST {{baseUrl}}/refreshTokens

### Update user
PUT {{baseUrl}}/users/modify/Test2
content-type: application/json

{
  "mail": "Test2"
}

### Get all users from db
GET {{baseUrl}}/users

### Get user with userId

GET {{baseUrl}}/users/169

### LogOut user
GET {{{{baseUrl}}}}/users/logout